all: prog-no-pruning prog-state-pruning

prog-no-pruning: prog-no-pruning.c
	gcc prog-no-pruning.c -g -O0 -o prog-no-pruning

prog-state-pruning: prog-state-pruning.c
	gcc prog-state-pruning.c -g -O0 -o prog-state-pruning
