{
  "EXPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
  .insns = {
	BPF_MOV64_IMM(BPF_REG_2, 1000),
    BPF_MOV64_REG(BPF_REG_3, BPF_REG_10),
    BPF_ALU64_IMM(BPF_DIV, BPF_REG_2, 3),
    BPF_JMP_IMM(BPF_JNE, BPF_REG_2, 0, 2),
    BPF_ST_MEM(BPF_DW, BPF_REG_3, -120, 200),
	BPF_JMP_IMM(BPF_JA, 0, 0, 1),
	BPF_ST_MEM(BPF_DW, BPF_REG_3, -120, -10),
    BPF_LDX_MEM(BPF_DW, BPF_REG_6, BPF_REG_3, -120),
    // Allocate
    BPF_LD_MAP_FD(BPF_REG_1, 0),
    BPF_MOV64_IMM(BPF_REG_2, 512),
    BPF_MOV64_IMM(BPF_REG_3, 0),
    BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_ringbuf_reserve),
    BPF_JMP_IMM(BPF_JNE, BPF_REG_0, 0, 1),
    BPF_EXIT_INSN(),
    //
    BPF_MOV64_REG(BPF_REG_7, BPF_REG_0),
    BPF_ALU64_REG(BPF_ADD, BPF_REG_7, BPF_REG_6),
    BPF_ST_MEM(BPF_DW, BPF_REG_7, 0, 36),
	// Release
	BPF_MOV64_REG(BPF_REG_1, BPF_REG_0),
	BPF_MOV64_IMM(BPF_REG_2, 0),
	BPF_RAW_INSN(BPF_JMP | BPF_CALL, 0, 0, 0, BPF_FUNC_ringbuf_submit),
	BPF_MOV64_IMM(BPF_REG_0, 0),
    BPF_EXIT_INSN(),
  },
  .fixup_map_ringbuf = {8},
  .result  = ACCEPT,
  .flags = BPF_F_TEST_STATE_FREQ,
  .result_unpriv = REJECT,
  .errstr_unpriv = "math between ringbuf_mem pointer and register with unbounded min value is not allowed",
},
